### ISSUE TITLE
1. Header Links

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/C3_HTML#1]
Linkurile de social, news si search nu fac nimic la mine - firefox. (pe nici o varianta de header)

**Comment by arlad** [comment]
Tre sa fie in HTML ca si in psd? Nu facem asta la UberMenu in WP?

**Comment by andreimarin90** [comment]
Astea trebuie facute aici, nu tin de uber

**Comment by arlad** [comment]
Done.
